name: AI – Create Blog Issue (safe)

on:
  schedule:
    # ⏰ ajuste para o seu horário/intervalo (UTC). Ex.: toda terça às 14:13 UTC (11:13 BRT)
    - cron: "13 14 * * 2"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

concurrency:
  group: ai-issue-bot
  cancel-in-progress: false

jobs:
  ai_issue:
    runs-on: ubuntu-latest
    # Use um Environment protegido (Settings > Environments) e coloque o OPENAI_API_KEY lá
    environment: prod

    env:
      LABELS: "post, curiosidade, publicar"
      TOPIC_POOL: "DevOps,Kubernetes,OKD,Keycloak,AWS,Terraform,Observabilidade,Dynatrace,Grafana,CI/CD,Segurança,Redis,Nginx,Traefik,PostgreSQL,MySQL,PHP,Node.js,Autoscaling,HPA,Cost Optimization"
      TONE: "Prático, direto, com curiosidade inicial e exemplo mínimo executável"
      MIN_WORDS: "220"
      MAX_WORDS: "420"
      SITE_NAME: "deployman.com.br"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --disable-pip-version-check --no-cache-dir openai==1.35.13

      - name: Generate issue with AI
        id: gen
        env:
          # ⚠️ pega do Environment "prod"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          python scripts/generate_issue.py

      - name: Create Issue from file
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ${{ steps.gen.outputs.title }}
          content-filepath: ${{ steps.gen.outputs.file }}
          labels: ${{ env.LABELS }}
